### PR TITLE
Update `php-parser`

### PR DESCRIPTION
**Pull request by joshuaspence**
Updates the version of the `php-parser` dependency.

### CODE REVIEW

**Comment by remicollet** [comment]
Notice: current version is 3.0.2 not 2.0. 
And v3 is recommended for PHP 7.1

And allowing various version seems a good idea (psysh or jeremeamia/superclosure does this)

**Comment by llaville** [comment]
Next version 4.1 will use php-parser 3.x, and 4.0 still keep constraint to 1.x

**Comment by joshuaspence** [comment]
I'm not sure that I understand. In `master`, the `php-parser` dependency is still pinned to `~1.4`. The problem is that `php-reflect` claims to support PHP 5.4, but version 3 of `php-parser` requires PHP 5.5.

**Comment by llaville** [comment]
We keep LTS (Long Time Support) with PHP_Reflect 4.0.x that depends of php_parser 1.4.x 
And we don't want to break BC with other application that use php_reflect 4.0

Future version of PHP_Reflect will use the new engine 3.x of php-parser and only php-reflect 4.1 or greater.
To be honest I don't know if I'll have enough time to release one day a new version : but this is the plan !

**Comment by joshuaspence** [comment]
OK, so there are no plans to support version 2.x of `php-parser`?

**Comment by llaville** [comment]
No plan to support version 2.x of php-parser / I'll directly use the version 3.x (if one day a release a new version of php-refflec)

**Comment by llaville** [comment]
Good new: PHP-Reflect 4.1 stable will be released tomorrow and will support nikic/php-parser 2.1

**Comment by llaville** [comment]
Delayed due to LICENCE file missing in external dependency. See https://github.com/zendframework/ZendDiagnostics/issues/77 (Thanks to Remi Collet)

**Comment by llaville** [comment]
Final code (except LICENSE for ZendDiagnostics missing) is now available on branch 4.1

Unit Tests with PHP 5.6.30 and PHP 7.0.15 (on PHPUnit 5.7.14) are all passed !

So waiting for this license now ...

**Comment by llaville** [comment]
As ZendDiagnostics package seems no more maintained, I'll rollback this feature `diagnose:run` command, and publish a new version next monday

**Comment by llaville** [comment]
4.1.0 was just been released

**Pull request closed without merging**
